apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiptap-collab-server.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiptap-collab-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  LICENSE_KEY: {{ .Values.secrets.LICENSE_KEY | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  API_SECRET: {{ .Values.secrets.API_SECRET | quote }} 