apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiptap-collab-server.name" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiptap-collab-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tiptap-collab-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: collab
      protocol: TCP
      port: {{ .Values.service.ports.collab }}
      targetPort: collab
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api }}
      targetPort: api
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics 