version: '3.8'

services:
  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001

  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend 